## Servicio para el productor
apiVersion: v1
kind: Service
metadata:
  name: productor-svc
spec:
  selector:
    app: productor
  ports:
    - port: 5000
      targetPort: 5000
---
## Servicio para el cliente
apiVersion: v1
kind: Service
metadata:
  name: cliente-svc
spec:
  type: NodePort
  selector:
    app: cliente
  ports:
    - port: 80
      targetPort: 8081
      nodePort: 30007