apiVersion: apps/v1
kind: Deployment
metadata:
  name: cliente-web
spec:
  selector:
    matchLabels:
      app: cliente-web
  template:
    metadata:
      labels:
        app: cliente-web
    spec:
      containers:
      - name: redis-commander
        image: rediscommander/redis-commander:latest
        ports:
        - containerPort: 8081
        env:
        - name: REDIS_HOSTS
          value: "local:bd-svc:6379:0:redispass123" 
---
apiVersion: v1
kind: Service
metadata:
  name: cliente-svc
spec:
  type: NodePort
  selector:
    app: cliente-web
  ports:
    - port: 80
      targetPort: 8081
      nodePort: 30001